all:
	@make -C ./Mandatory

bonus:
	@make -C ./Bonus

clean:
	@make clean -C ./Mandatory
	@make clean -C ./Bonus

fclean:
	@make fclean -C ./Mandatory
	@make fclean -C ./Bonus

re:
	@make re -C ./Mandatory

.PHONY: bonus